package com.aditya.inventory.model;

import java.math.BigDecimal;

import org.hibernate.annotations.UuidGenerator;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * The ProductStock entity is the main entity which represents
 * a unit of stock uniquely identified by its SKU
 * which is a unique aplha-numeric string generated by the UUID generation strategy
 *
 * @author Aditya Yadav
 */

@Entity
public class ProductStock {

  /**
   * The default constructor for the ProductStock entity
   */
  public ProductStock() {
    this.sku = "";
    this.name = "";
    this.description = "";
    this.price = new BigDecimal("0.0");
    this.quantity = 0;
    this.category = "All";
  }

  /**
   * The main constructor for the ProductStock entity which requires
   * all fields of the class except the id field which is auto-generated
   * by the persistence library.
   * 
   * @param sku
   * @param name
   * @param description
   * @param price
   * @param quantity
   * @param category
   */
  public ProductStock(String sku, String name, String description,
      BigDecimal price, Integer quantity, String category) {
    this.sku = sku;
    this.name = name;
    this.description = description;
    this.price = price;
    this.quantity = quantity;
    this.category = category;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id", unique = true, nullable = false)
  Long id;

  /**
   * Stock Keeping Unit (SKU) is a randomly generated
   * alphanumeric value which uniquely indentifies a product stock in the
   * inventory
   */
  @UuidGenerator
  @Column(name = "sku", unique = true, nullable = false)
  String sku;

  /**
   * The name of the product as a character string
   */
  @Column(name = "p_name", unique = true, nullable = false)
  String name;

  /**
   * The product description associated with the product stock which may include
   * details about the product's type, dimensions, properties and more.
   */
  @Column(name = "description")
  String description;

  /**
   * The total price of the whole product stock.
   */
  @Column(name = "price", nullable = false)
  BigDecimal price;

  /**
   * The number of individual items of the product in the product stock.
   */
  @Column(name = "quantity", nullable = false)
  Integer quantity;

  /**
   * The broader category of products represented as a character string for
   * simplicity.
   */
  @Column(name = "category")
  String category;

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

}