spring.application.name=high-concurrency-inventory
server.port=8082

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=${DB_USER:myuser}
spring.datasource.password=${DB_PASSWORD:mysecretpassword}

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true